exclude:
  - "/vendor/"
  - "/node_modules/"
  - "/assets/_src_img/"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

include:
  - _pages

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: Raster Foundry
subtitle: "A template to get started on"
url: ""
baseurl: ""

# Build settings
markdown: kramdown

# Sass is off loaded to gulp.js
# sass:
#     sass_dir: assets/_scss
#     style: compressed

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
