backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
show_preview_links: true
media_folder: "uploads" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Global"
    name: "global"
    delete: false
    editor:
      preview: false
    files:
      - label: "Social Media"
        name: "social"
        file: "_data/social_media.yml"
        fields:
          - label: platform
            name: platform
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Link, name: link, widget: string }
      - label: "Footer"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - { label: Footer subtitle, name: footer-subtitle, widget: string }
          - { label: Footer title, name: footer-title, widget: string }
          - { label: Footer location, name: location, widget: string }
          - { label: Footer contact, name: contact-link, widget: string }
          - { label: Footer company label, name: company-title, widget: string }
          - label: Company links
            name: company-links
            widget: list
            allow_add: true
            fields:
              - { label: Link, name: link, widget: string }
          - {
              label: Footer services label,
              name: services-title,
              widget: string,
            }
          - label: Services links
            name: services-links
            widget: list
            allow_add: true
            fields:
              - { label: Link, name: link, widget: string }
  - label: "Pages"
    name: "home"
    delete: false
    editor:
      preview: false
    files:
      - label: "Home Pages"
        name: "home"
        file: "_data/home.yml"
        fields:
          - { label: Hero title, name: hero-title, widget: string }
          - { label: Hero body, name: hero-body, widget: text }
          - {
              label: Capabilities subtitle,
              name: capabilities-subtitle,
              widget: string,
            }
          - {
              label: Capabilities title,
              name: capabilities-title,
              widget: string,
            }
          - label: "capabilities"
            name: "capabilities"
            widget: "list"
            fields:
              - {
                  label: capability title,
                  name: capability-title,
                  widget: string,
                }
              - {
                  label: capability icon,
                  name: capability-icon,
                  widget: string,
                }
              - {
                  label: capability statement,
                  name: capability-statement,
                  widget: text,
                }
              - {
                  label: capability image,
                  name: capability-image,
                  widget: image,
                  allow_multiple: false,
                }
          - {
              label: industries subtitle,
              name: industries-subtitle,
              widget: string,
            }
          - { label: industries title, name: industries-title, widget: string }
          - label: "industries"
            name: "industries"
            widget: "list"
            fields:
              - { label: industry title, name: industry-title, widget: string }
              - { label: industry link, name: industry-link, widget: string }
              - {
                  label: industry image,
                  name: industry-image,
                  widget: image,
                  allow_multiple: false,
                }
              - {
                  label: industry image alt,
                  name: industry-image-alt,
                  widget: string,
                }
          - { label: clients subtitle, name: clients-subtitle, widget: string }
          - { label: clients title, name: clients-title, widget: string }
          - label: "clients"
            name: "clients"
            widget: "list"
            fields:
              - { label: client name, name: client-name, widget: string }
              - {
                  label: client logo,
                  name: client-logo,
                  widget: image,
                  allow_multiple: false,
                }
          - label: "testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: testimonial, name: testimonial, widget: text }
              - {
                  label: testimonial name,
                  name: testimonial-name,
                  widget: string,
                }
              - {
                  label: testimonial position,
                  name: testimonial-position,
                  widget: string,
                }
              - {
                  label: testimonial image,
                  name: testimonial-image,
                  widget: image,
                  allow_multiple: false,
                }
      - label: "Infrastructure Management"
        name: "infrastructure_management"
        file: "_data/infrastructure_management.yml"
        fields:
          - { label: Hero subtitle, name: hero-subtitle, widget: string }
          - { label: Hero title, name: hero-title, widget: text }
          - {
              label: Hero image,
              name: hero-image,
              widget: image,
              allow_multiple: false,
            }
          - { label: Page copy, name: page-copy, widget: markdown }
          - {
              label: Page image,
              name: page-image,
              widget: image,
              allow_multiple: false,
            }
          - label: "projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: project title, name: project-title, widget: string }
              - {
                  label: project subtitle,
                  name: project-subtitle,
                  widget: string,
                }
              - {
                  label: project statement,
                  name: project-statement,
                  widget: string,
                }
              - {
                  label: project image,
                  name: project-image,
                  widget: image,
                  allow_mulitple: false,
                }
              - { label: project color, name: project-color, widget: string }
